package com.springmvc.pojo;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSM_TEST.ID
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSM_TEST.NUM
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSM_TEST.NAME
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSM_TEST.DISTRICT
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSM_TEST.CITY
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSM_TEST.PROVINCE
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSM_TEST.ID
     *
     * @return the value of T_SSM_TEST.ID
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSM_TEST.ID
     *
     * @param id the value for T_SSM_TEST.ID
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSM_TEST.NUM
     *
     * @return the value of T_SSM_TEST.NUM
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSM_TEST.NUM
     *
     * @param num the value for T_SSM_TEST.NUM
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSM_TEST.NAME
     *
     * @return the value of T_SSM_TEST.NAME
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSM_TEST.NAME
     *
     * @param name the value for T_SSM_TEST.NAME
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSM_TEST.DISTRICT
     *
     * @return the value of T_SSM_TEST.DISTRICT
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSM_TEST.DISTRICT
     *
     * @param district the value for T_SSM_TEST.DISTRICT
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSM_TEST.CITY
     *
     * @return the value of T_SSM_TEST.CITY
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSM_TEST.CITY
     *
     * @param city the value for T_SSM_TEST.CITY
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSM_TEST.PROVINCE
     *
     * @return the value of T_SSM_TEST.PROVINCE
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSM_TEST.PROVINCE
     *
     * @param province the value for T_SSM_TEST.PROVINCE
     *
     * @mbggenerated Tue Jun 05 17:26:14 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}