package com.springmvc.pojo;

import java.math.BigDecimal;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ID
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USERNAME
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PASSWORD
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.AGE
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    private BigDecimal age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.GENDER
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    private BigDecimal gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ID
     *
     * @return the value of USERS.ID
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ID
     *
     * @param id the value for USERS.ID
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USERNAME
     *
     * @return the value of USERS.USERNAME
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USERNAME
     *
     * @param username the value for USERS.USERNAME
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD
     *
     * @return the value of USERS.PASSWORD
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD
     *
     * @param password the value for USERS.PASSWORD
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.AGE
     *
     * @return the value of USERS.AGE
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public BigDecimal getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.AGE
     *
     * @param age the value for USERS.AGE
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public void setAge(BigDecimal age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.GENDER
     *
     * @return the value of USERS.GENDER
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public BigDecimal getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.GENDER
     *
     * @param gender the value for USERS.GENDER
     *
     * @mbggenerated Mon Jun 04 18:19:48 CST 2018
     */
    public void setGender(BigDecimal gender) {
        this.gender = gender;
    }
}